apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-${BRANCH}-deployment
  labels:
    app: grocery-${BRANCH}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocery-${BRANCH}
  template:
    metadata:
      labels:
        app: grocery-${BRANCH}
    spec:
      containers:
      - name: grocery-${BRANCH}
        image: ${IMAGE}
        env:
        - name: PORT
          value: "${PORT}"
        - name: DB_HOST
          value: ${DB_HOST}
        - name: DB_NAME
          value: ${DB_NAME}
        - name: DB_USER
          value: ${DB_USER}
        - name: DB_PASSWORD
          value: ${DB_PASSWORD}
        ports:
        - containerPort: ${PORT}
          name: backend-http

---
kind: Service
apiVersion: v1
metadata:
  name: grocery-${BRANCH}-service
spec:
  selector:
    app: grocery-${BRANCH}
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    name: http
    targetPort: backend-http